logging:
  level: DEBUG

ecard:
  url: http://localhost:8898
  token: 123

custom:
  management:
    security:
      access: hasIpAddress('127.0.0.1') or hasIpAddress('0:0:0:0:0:0:0:1')
  connection:
    location:
      server: http://localhost:8898

log-api:
    uri: https://log.apitest.cc.ncu.edu.tw/log/api
